### ISSUE TITLE
Login error message

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#33]
Since the salt is not used anymore I think the error message should be changed from "Invalid Username, Password or Salt"

**Comment by alecgorge** [comment]
Damn it old habits did hard.

I'll get that fixed.

Sent from my iPhone

On Oct 10, 2013, at 6:15 AM, godgodgodgo notifications@github.com wrote:

Since the salt is not used anymore I think the error message should be
changed from "Invalid Username, Password or Salt"

—
Reply to this email directly or view it on
GitHubhttps://github.com/alecgorge/AdminiumIssues/issues/33
.
