### ISSUE TITLE
Error messages not in front

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#34]
The red error messages are showing underneath the top bar of the app.
The messages should either be moved to the front of the whole app or lowered to be in the main content area.

**Comment by alecgorge** [comment]
This is fixed in the release version.

It was one of the last things I caught.

Sent from my iPhone

On Oct 10, 2013, at 6:16 AM, godgodgodgo notifications@github.com wrote:

The red error messages are showing underneath the top bar of the app.
The messages should either be moved to the front of the whole app or
lowered to be in the main content area.

—
Reply to this email directly or view it on
GitHubhttps://github.com/alecgorge/AdminiumIssues/issues/34
.
